#!/usr/bin/env node
/**
 * easy-peasy-build
 *
 * Generates an llms-full.txt from local documentation files.
 * Concatenates Markdown docs and OpenAPI/AsyncAPI specs into the
 * <!-- FILE: path --> format understood by easy-peasy-mcp.
 *
 * Usage:
 *   node build.js \
 *     --docs ./guides \
 *     --docs ./api-reference \
 *     --openapi ./openapi \
 *     --asyncapi ./asyncapi \
 *     --title "My Project" \
 *     --output ./llms-full.txt
 *
 * --docs can be repeated for multiple directories.
 * Omit --output to print to stdout.
 */

import { readFileSync, writeFileSync, readdirSync, statSync, existsSync } from "fs";
import { join, relative, resolve, extname } from "path";
import { parseArgs } from "util";
import { fileURLToPath } from "url";

// ---------------------------------------------------------------------------
// Core build function (exported for use by index.js --rebuild)
// ---------------------------------------------------------------------------

/**
 * Build llms-full.txt content from docs and spec directories.
 *
 * @param {{
 *   docs?: string[],
 *   openapi?: string,
 *   asyncapi?: string,
 *   title?: string,
 *   output?: string
 * }} options
 * @returns {string} the generated content
 */
export function build({ docs = [], openapi, asyncapi, title = "Documentation", output } = {}) {
  const sections = [];

  sections.push(
    `<!-- Generated by easy-peasy-build on ${new Date().toISOString()} -->`,
    `<!-- Title: ${title} -->`,
    ""
  );

  for (const dir of docs) {
    if (!existsSync(dir)) {
      console.warn(`Warning: docs directory not found, skipping: ${dir}`);
      continue;
    }
    const files = collectFiles(dir, [".md", ".mdx"]);
    for (const filePath of files) {
      const rel = relative(process.cwd(), filePath);
      const content = readFileSync(filePath, "utf8").trimEnd();
      sections.push(`<!-- FILE: ${rel} -->`, content, "");
    }
  }

  if (openapi) appendSpecDir(sections, openapi, "openapi");
  if (asyncapi) appendSpecDir(sections, asyncapi, "asyncapi");

  const result = sections.join("\n");

  if (output) {
    writeFileSync(output, result, "utf8");
    console.error(`Written to ${output}  (${formatBytes(Buffer.byteLength(result, "utf8"))})`);
  }

  return result;
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

/**
 * Recursively collect files matching the given extensions, sorted by path.
 * @param {string} dir
 * @param {string[]} extensions  e.g. [".md", ".mdx"]
 * @returns {string[]}
 */
function collectFiles(dir, extensions) {
  const results = [];
  for (const entry of readdirSync(dir).sort()) {
    const full = join(dir, entry);
    const stat = statSync(full);
    if (stat.isDirectory()) {
      results.push(...collectFiles(full, extensions));
    } else if (extensions.includes(extname(entry).toLowerCase())) {
      results.push(full);
    }
  }
  return results;
}

/**
 * Append all JSON/YAML/YML spec files from a directory as FILE sections.
 * @param {string[]} sections
 * @param {string} dir
 * @param {string} kind  "openapi" | "asyncapi"
 */
function appendSpecDir(sections, dir, kind) {
  if (!existsSync(dir)) {
    console.warn(`Warning: ${kind} directory not found, skipping: ${dir}`);
    return;
  }
  const SPEC_EXTS = [".json", ".yaml", ".yml"];
  for (const file of readdirSync(dir).sort()) {
    const ext = extname(file).toLowerCase();
    if (!SPEC_EXTS.includes(ext)) continue;
    const filePath = join(dir, file);
    const rel = relative(process.cwd(), filePath);
    const content = readFileSync(filePath, "utf8").trimEnd();
    const fence = ext === ".json" ? "json" : "yaml";
    sections.push(
      `<!-- FILE: ${rel} -->`,
      `\`\`\`${fence}`,
      content,
      "```",
      ""
    );
  }
}

/**
 * @param {number} bytes
 * @returns {string}
 */
function formatBytes(bytes) {
  if (bytes < 1024) return `${bytes} B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)} MB`;
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

if (process.argv[1] === fileURLToPath(import.meta.url)) {
  const { values: args } = parseArgs({
    args: process.argv.slice(2),
    options: {
      docs:     { type: "string", multiple: true },  // markdown source dirs (repeatable)
      openapi:  { type: "string" },                  // OpenAPI spec directory
      asyncapi: { type: "string" },                  // AsyncAPI spec directory
      title:    { type: "string" },                  // project title for header
      output:   { type: "string" },                  // output file path (omit → stdout)
    },
    strict: false,
  });

  const docsDirs    = (args.docs ?? []).map((d) => resolve(d));
  const openapiDir  = args.openapi  ? resolve(args.openapi)  : null;
  const asyncapiDir = args.asyncapi ? resolve(args.asyncapi) : null;
  const title       = args.title ?? "Documentation";
  const outputPath  = args.output   ? resolve(args.output)   : null;

  if (docsDirs.length === 0 && !openapiDir && !asyncapiDir) {
    console.error(
      "Error: provide at least one of --docs <dir>, --openapi <dir>, --asyncapi <dir>."
    );
    process.exit(1);
  }

  const result = build({ docs: docsDirs, openapi: openapiDir, asyncapi: asyncapiDir, title, output: outputPath });
  if (!outputPath) process.stdout.write(result);
}
